apiVersion: v1
kind: Secret
metadata:
  name: grafana-init-user
  labels:
    app.kubernetes.io/name: k8s-moitoring
    app.kubernetes.io/component: grafana
type: Opaque
data:
  # By default, admin-user is set to `admin`; They should be in base64 format: echo -n "TEST"|base64
  admin-user: 
  admin-password: 